version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: nexusstore-postgres
    restart: always
    environment:
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nexusstore
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: